# -*- coding: utf-8 -*-
"""KNN_수업.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_5jN_l5yiAAOwlJjyBarmDtsfWhUcMc
"""

import pandas as pd
import numpy as np
import seaborn as sns
import pandas as pd

from sklearn.datasets import load_iris

iris = load_iris()

iris.keys()

iris.target_names

iris.feature_names

iris.target

from sklearn.model_selection import train_test_split

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

from sklearn import metrics

print("Accuracy:", knn.score(X_test, y_test))

from sklearn import metrics

k_range = range(1,50)
scores = {}
scores_list = []
for k in k_range : 
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train,y_train)
  y_pred = knn.predict(X_test)
  scores[k] = metrics.accuracy_score(y_test, y_pred)
  scores_list.append(metrics.accuracy_score(y_test,y_pred))

import matplotlib.pyplot as plt

plt.plot(k_range, scores_list)
plt.xlabel('k 값')
plt.ylabel('Accuracy')

