# -*- coding: utf-8 -*-
"""머신러닝 2강_수업.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ANx1ebLH-QgzjpT0W2SliYfM6ofIrx2z
"""

import numpy as np

data = [1,2,3,4,5]

arr = np.array(data)

print(arr.shape)

print(arr.dtype)

np.zeros((9,2))

np.arange(20)

import matplotlib.pyplot as plt
import pandas as pd

students_name = ["Curry", "Durant", "Duncan", "Green"]

math = [99, 35, 23, 86]

result = pd.DataFrame({
    "Name": students_name,
    "Math": math
})

print(result)

plt.bar(students_name, math)

plt.show()
